config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'bitcoin/index'
  get 'ethereum/index'
  get 'contact/index'

  put 'preferences/update'

  post 'contact/submit'

  root 'welcome#index'

  resources :prefs

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bitcoin_preference.rb
class BitcoinPreference < ApplicationRecord
  validates :fiat_currency, presence: true

  private
    def bitcoinpreference_params
      params.require(:bitcoin_preferences).permit(:fiat_currency)
    end
end

app/models/bitcoin_price.rb
class BitcoinPrice < ApplicationRecord
  validates :price, presence: true
  validates :time, presence: true
end

app/models/currency.rb
class Currency < ApplicationRecord

  validates :currency_type, presence: true
  has_many :prices, :foreign_key => 'crypto_id'

  private
    def currency_params
      params.require(:currencies).require(:currency_type)
    end
end

app/models/preference.rb
class Preference < ApplicationRecord
  validates :fiat_currency, presence: true
  validates :time_interval, presence: true

  private
    def preference_params
      params.require(:preferences).permit(:fiat_currency, :time_interval)
    end
end

app/models/price.rb
class Price < ApplicationRecord
  validates :price, presence: true
  validates :time, presence: true
  belongs_to :currency, :foreign_key => 'crypto_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bitcoin_controller.rb
class BitcoinController < ApplicationController

  def initialize
    super
    @default_fiat = 'GBP'
    @prefs_controller = PreferencesController.new
    @currency_controller = CurrencyController.new(currency_type: 'BTC', pref_controller: @prefs_controller)
  end

  def index
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def index
  end

  def submit
    name = params[:name]
    email = params[:email]
    comment = params[:message]

    # Pass obtained parameters straight to the mailer
    ContactMailer.send_contact_email(name, email, comment).deliver
    redirect_to bitcoin_index_path, notice: "Successfully sent contact message"
  end

end

app/controllers/currency_controller.rb
require 'cryptocompare'
require 'date'

class CurrencyController < ApplicationController

  def initialize(options = {})
    @currency = nil
    @prefs_controller = options[:pref_controller] || PreferencesController.new
    @ctype = options[:currency_type] || 'BTC'


    if Currency.where(currency_type: @ctype).empty?
      puts 'new currency object'
      @currency = Currency.create(:currency_type => @ctype)
      @currency.save!
    else
      puts 'currency object exists'
      self.obtainCurrencyModelFromDB
    end

    # Put latest price data from Cryptocompare into the currency model
    self.updatePrices

  end

  def processCryptoPriceObject(crypto_price_object, currency_object)
    # only save if response is HTTP OK (200)
    puts crypto_price_object

    # Only get first 3h of minute-by-minute values to improve loading performance
    if @prefs_controller.prefs.time_interval == "1m"
      restricted = 1
    end

    if crypto_price_object['Response'] == "Success"
      counter = 0
      crypto_price_object['Data'].each do | price |

        # stop after certain time if restricted = True
        if restricted == 1 && counter == 180
          break
        end

        # only take the closing price for each time interval, for now
        price_value = price['close']

        # time is a Unix timestamp, so convert
        price_time = Time.at(price['time']).to_datetime
        @currency.prices.create(:price => price_value, :time => price_time)
        puts 'attempted to create price'

        counter += 1
      end
      @currency.save
    else
      puts 'error retrieving data from cryptocompare'
    end
  end




  def updatePrices
    # Obtain the time interval from Preference
    @crypto_prices = nil
    puts 'updating prices now'
    unless @prefs_controller.prefs.nil?
      tinterval = @prefs_controller.prefs.time_interval
      if tinterval == "1m"
        @crypto_prices = Cryptocompare::HistoMinute.find(@currency.currency_type, @prefs_controller.prefs.fiat_currency)
        self.processCryptoPriceObject(@crypto_prices, @currency)
      elsif tinterval == "1h"
        @crypto_prices = Cryptocompare::HistoHour.find(@currency.currency_type, @prefs_controller.prefs.fiat_currency)
        puts 'calling pcpo'
        self.processCryptoPriceObject(@crypto_prices, @currency)
      elsif tinterval == "1d"
        @crypto_prices = Cryptocompare::HistoDay.find(@currency.currency_type, @prefs_controller.prefs.fiat_currency)
        self.processCryptoPriceObject(@crypto_prices, @currency)
      end
    end
  end

  def obtainCurrencyModelFromDB
    @currency = Currency.where(currency_type: @ctype).first
  end

  # Allow currency object to be obtained by other views and controllers
  attr_reader :currency

end

app/controllers/ethereum_controller.rb
class EthereumController < ApplicationController

  def initialize
    super
    @default_fiat = 'GBP'
    @prefs_controller = PreferencesController.new
    @currency_controller = CurrencyController.new(currency_type: 'ETH', pref_controller: @prefs_controller)
  end

  def index
  end

end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController

  def initialize
    # Make sure to initialise the ApplicationController if it is not already initialised
    super

    # Made in England, so default to Pound Sterling currency type
    @default_fiat = 'GBP'

    # Auto-create a preference model if it doesn't exist
    # Note: This is done here, because only one preference object is ever intended to exist.
    @prefs = nil
    if Preference.where(id: 1).empty?
      @prefs = Preference.create(:fiat_currency => @default_fiat, :time_interval => "1h")
      @prefs.save!
    else
      self.obtainPrefModelFromDB
    end
  end

  # No template is rendered by this action.
  def update
    @prefs.update(prefs_params)
    ActiveRecord::Base.connection.execute("DELETE FROM currencies WHERE 1")
    ActiveRecord::Base.connection.execute("DELETE FROM prices WHERE 1")
    if @prefs.save!
      redirect_to bitcoin_index_path, notice: 'Preferences successfully saved'
    else
      redirect_to bitcoin_index_path, notice: 'Preferences not saved'
    end
  end

  def obtainPrefModelFromDB
    @prefs = Preference.first
  end

  # Preference model object needs to be accessible to the btc/eth view so it can get settings
  attr_reader :prefs, :default_fiat

  # Strong parameters, used for update
  private
  def prefs_params
    params.require(:prefs).permit(:time_interval, :fiat_currency)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bitcoin_helper.rb
module BitcoinHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/currency_helper.rb
module CurrencyHelper
end

app/helpers/ethereum_helper.rb
module EthereumHelper
end

app/helpers/preferences_helper.rb
module PreferencesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bitcoin/index.html.erb
<%= render 'layouts/header', :prefs => @prefs_controller.prefs %>

<div class="text-center">
  <h1 style="font-size: 80px; color: #008975;">BTC - <%= @prefs_controller.prefs.fiat_currency %></h1>
  <h3 style="margin-bottom: 7vh;">Latest price (<%= @prefs_controller.prefs.time_interval %>): <%= @currency_controller.currency.prices.last.price %> <%=@prefs_controller.prefs.fiat_currency %></h3>
</div>


<% if @prefs_controller.prefs.time_interval == "1m" %>
  <%= line_chart @currency_controller.currency.prices.group_by_minute(:time).maximum(:price) %>
<% elsif @prefs_controller.prefs.time_interval == "1h" %>
  <%= line_chart @currency_controller.currency.prices.group_by_hour(:time).maximum(:price) %>
<% else %>
  <%= line_chart @currency_controller.currency.prices.group_by_day(:time).maximum(:price) %>
<% end %>

<%= render 'layouts/footer' %>

app/views/contact/index.html.erb
<%= render 'layouts/header' %>

<h2 class='text-center' style="color: #008975">Contact us</h2>

<div class="container">
  <%= form_tag contact_submit_path, method: 'post' do %>
    <%= label_tag :name, t('.name') %>
    <%= text_field_tag :name, '', title: t('.enter_name'), size: 5 %>
    <br />
    <%= label_tag :email, t('.email') %>
    <%= email_field_tag :email, '', title: t('.enter_email') %>
    <br />
    <%= label_tag :telephone, t('.telephone') %>
    <%= telephone_field_tag :telephone, '', title: t('.enter_telephone') %>
    <br />
    <%= label_tag :message, t('.message') %>
    <%= text_field_tag :message, '', title: t('.enter_message'), size: 100 %>

    <br />
    <%= submit_tag 'Submit' %>
  <% end %>

  <p id="notice"><%= notice %></p>
</div>


<%= render 'layouts/footer' %>

app/views/ethereum/index.html.erb
<%= render 'layouts/header', :prefs => @prefs_controller.prefs %>

<div class="text-center">
  <h1 style="font-size: 80px; color: #008975;">ETH - <%= @prefs_controller.prefs.fiat_currency %></h1>
  <h3 style="margin-bottom: 7vh;">Latest price (<%= @prefs_controller.prefs.time_interval %>): <%= @currency_controller.currency.prices.last.price %> <%= @prefs_controller.prefs.fiat_currency %></h3>
</div>

<% if @prefs_controller.prefs.time_interval == "1m" %>
  <%= line_chart @currency_controller.currency.prices.group_by_minute(:time).maximum(:price) %>
<% elsif @prefs_controller.prefs.time_interval == "1h" %>
  <%= line_chart @currency_controller.currency.prices.group_by_hour(:time).maximum(:price) %>
<% else %>
  <%= line_chart @currency_controller.currency.prices.group_by_day(:time).maximum(:price) %>
<% end %>

<%= render 'layouts/footer' %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-center" style="font-size:14px; color: #008975; margin-top:1vh;">Copyright Alex Potter. All rights reserved.</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top navbar-custom" style="width: 100%">
  <%= image_tag('logo.svg', :style => 'width: 50%; height: auto; margin-left: -17vw; margin-top: -5vh;') %>

  <div class="col-xs-4">
    <%= link_to(bitcoin_index_path) do %>
      <%= content_tag(:button, '<b>Bitcoin</b>'.html_safe, :class => 'btn btn-outline-dark btn-md btn-navbar-custom') %>
    <% end %>

    <%= link_to(ethereum_index_path) do %>
      <%= content_tag(:button, '<b>Ethereum</b>'.html_safe, :class => 'btn btn-outline-dark btn-md btn-navbar-custom') %>
    <% end %>

    <%= link_to(contact_index_path) do %>
      <%= content_tag(:button, '<b>CONTACT</b>'.html_safe, :class => 'btn btn-outline-dark btn-md btn-navbar-custom') %>
    <% end %>

    <button type="button" class="btn btn-outline-dark btn-md btn-navbar-custom" data-toggle="modal" data-target="#settings-modal"><b>OPTIONS</b></button>
  </div>

  <div id="settings-modal" class="modal fade" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title text-left">Pretium Options</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>

        <div class="modal-body">
          <%= simple_form_for(:prefs, :url => preferences_update_path, html: { :method => :put, class: 'form-inline' }) do |form| %>
            <%= form.input :time_interval, collection: ["1m", "1h", "1d"] %>
            <%= form.input :fiat_currency, collection: ["USD", "EUR", "GBP", "CAD"] %>
            <%= form.button :submit %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pretium</title>
    <%= csrf_meta_tags %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="text-center" style="width: 100%">
  <%= image_tag('logo.svg', :style => 'margin-left: -9vw;', :alt => 'pretium') %>
  <%= link_to(bitcoin_index_path) do %>
    <%= content_tag(:button, '<b>Get started</b>'.html_safe, :class => 'btn btn-outline-dark btn-lg btn-navbar-custom') %>
  <% end %>
</div>

<%= render 'layouts/footer' %>